#!/bin/sh
set -e

# TODO: implement debconf support that is maintainable without duplicating the config
# Source debconf library.
#. /usr/share/debconf/confmodule
#
## Ask for the Matrix homeserver name, address and port.
#db_input high matron-server/hostname || true
#db_go
#
#db_input low matron-server/address || true
#db_go
#
#db_input medium matron-server/port || true
#db_go

exit 0
