#!/bin/sh
set -e

#. /usr/share/debconf/confmodule

MATRON_SERVER_CONFIG_PATH=/etc/matron-server
MATRON_SERVER_DATABASE_PATH=/var/lib/matron-server
CONDUIT_DATABASE_PATH_SYMLINK=/var/lib/matrix-conduit
CONDUWUIT_DATABASE_PATH_SYMLINK=/var/lib/conduwuit

case $1 in
  purge)
    # Remove debconf changes from the db
    #db_purge

    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."

    #

    if [ -d "$MATRON_SERVER_CONFIG_PATH" ]; then
      if test -L "$MATRON_SERVER_CONFIG_PATH"; then
        echo "Deleting matron-server configuration files"
        rm -v -r "$MATRON_SERVER_CONFIG_PATH"
      fi
    fi

    if [ -d "$MATRON_SERVER_DATABASE_PATH" ]; then
      if test -L "$MATRON_SERVER_DATABASE_PATH"; then
        echo "Deleting matron-server database directory"
        rm -r "$MATRON_SERVER_DATABASE_PATH"
      fi
    fi

    if [ -d "$CONDUIT_DATABASE_PATH_SYMLINK" ]; then
      if test -L "$CONDUIT_DATABASE_SYMLINK"; then
        echo "Removing matrix-conduit symlink"
        rm -r "$CONDUIT_DATABASE_PATH_SYMLINK"
      fi
    fi

    if [ -d "$CONDUWUIT_DATABASE_PATH_SYMLINK" ]; then
      if test -L "$CONDUWUIT_DATABASE_SYMLINK"; then
        echo "Removing conduwuit symlink"
        rm -r "$CONDUWUIT_DATABASE_PATH_SYMLINK"
      fi
    fi
    ;;
esac

#DEBHELPER#
