#!/bin/sh
set -e

# TODO: implement debconf support that is maintainable without duplicating the config
#. /usr/share/debconf/confmodule

MATRON_SERVER_DATABASE_PATH=/var/lib/matron-server
MATRON_SERVER_CONFIG_PATH=/etc/matron-server

case "$1" in
  configure)
    # Create the `matron-server` user if it does not exist yet.
    if ! getent passwd matron-server > /dev/null ; then
      echo 'Adding system user for the matron-server Matrix homeserver' 1>&2
      adduser --system --group --quiet \
        --home "$MATRON_SERVER_DATABASE_PATH" \
        --disabled-login \
        --shell "/usr/sbin/nologin" \
        matron-server
    fi

    # Create the database path if it does not exist yet and fix up ownership
    # and permissions for the config.
    mkdir -v -p "$MATRON_SERVER_DATABASE_PATH"

    # symlink the previous location for compatibility if it does not exist yet.
    if ! test -L "/var/lib/matrix-conduit" ; then
        ln -s -v "$MATRON_SERVER_DATABASE_PATH" "/var/lib/matrix-conduit"
    fi
    if ! test -L "/var/lib/conduwuit" ; then
        ln -s -v "$MATRON_SERVER_DATABASE_PATH" "/var/lib/conduwuit"
    fi

    chown -v matron-server:matron-server -R "$MATRON_SERVER_DATABASE_PATH"
    chown -v matron-server:matron-server -R "$MATRON_SERVER_CONFIG_PATH"

    chmod -v 740 "$MATRON_SERVER_DATABASE_PATH"

    echo ''
    echo 'Make sure you edit the example config at /etc/matron-server/matron-server.toml before starting!'
    echo 'To start the server, run: systemctl start matron-server.service'
    echo ''

    ;;
esac

#DEBHELPER#
